import sharp from 'sharp';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const page = process.argv[2];
if (!['about', 'projects', 'research', 'blog', 'contact'].includes(page)) throw new Error('Supply a known page');
const root = path.resolve('docs/plans/scenic-heroes/assets', page);
const source = JSON.parse(await readFile(path.join(root, 'sources.json'), 'utf8'));
const output = path.resolve('public/scenic-heroes', page);
await mkdir(output, { recursive: true });
const manifest = { page, generator: source.generator, assets: [] };
const descriptors = {};
for (const asset of source.assets) {
  const original = await readFile(asset.source);
  const metadata = await sharp(original).metadata();
  let crop = { left: 0, top: 0, width: metadata.width, height: metadata.height };
  if (asset.cutout) {
    if (!metadata.hasAlpha) throw new Error(`${asset.id}: alpha missing`);
    const { data, info } = await sharp(original).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    let left = info.width, top = info.height, right = 0, bottom = 0, transparent = 0;
    for (let y = 0; y < info.height; y++) for (let x = 0; x < info.width; x++) {
      const alpha = data[(y * info.width + x) * 4 + 3];
      if (alpha <= 8) { transparent++; continue; }
      left = Math.min(left, x); top = Math.min(top, y); right = Math.max(right, x); bottom = Math.max(bottom, y);
    }
    if (transparent / (info.width * info.height) < .12) throw new Error(`${asset.id}: insufficient transparent area`);
    // Keep a small alpha gutter so interpolation never samples a clipped edge.
    left = Math.max(0, left - 4); top = Math.max(0, top - 4);
    crop = { left, top, width: Math.min(info.width - left, right - left + 5), height: Math.min(info.height - top, bottom - top + 5) };
  }
  const variants = asset.cutout ? [asset.width] : [768, 1280, 1536];
  for (const width of variants) {
    const name = asset.cutout ? asset.id : `${asset.id}-${width}`;
    const bytes = await sharp(original).extract(crop).resize({ width, withoutEnlargement: true }).webp({ quality: asset.cutout ? 83 : 77, effort: 6, alphaQuality: 95 }).toBuffer();
    await writeFile(path.join(output, `${name}.webp`), bytes);
    const m = await sharp(bytes).metadata();
    const descriptor = { src: `/scenic-heroes/${page}/${name}.webp`, width: m.width, height: m.height };
    descriptors[name] = descriptor;
    manifest.assets.push({ id: name, ...descriptor, bytes: bytes.length, alpha: !!m.hasAlpha, crop, sha256: createHash('sha256').update(bytes).digest('hex'), source: asset.source, sourceSha256: createHash('sha256').update(original).digest('hex') });
  }
}
await writeFile(path.join(root, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
await writeFile(path.resolve('components/scenic-hero/scenes', `${page}-assets.js`), `// Generated by scripts/scenic-heroes/export-assets.mjs; edit sources.json, then export.\nexport const assets = ${JSON.stringify(descriptors, null, 2)};\n`);
console.log(JSON.stringify(manifest.assets.map(({ id, bytes, width, height, alpha }) => ({ id, bytes, width, height, alpha })), null, 2));
