// Generated by scripts/scenic-heroes/export-assets.mjs; edit sources.json, then export.
export const assets = {
  "forest-768": {
    "src": "/scenic-heroes/about/forest-768.webp",
    "width": 768,
    "height": 512
  },
  "forest-1280": {
    "src": "/scenic-heroes/about/forest-1280.webp",
    "width": 1280,
    "height": 853
  },
  "forest-1536": {
    "src": "/scenic-heroes/about/forest-1536.webp",
    "width": 1536,
    "height": 1024
  },
  "branch": {
    "src": "/scenic-heroes/about/branch.webp",
    "width": 1400,
    "height": 528
  },
  "foliage": {
    "src": "/scenic-heroes/about/foliage.webp",
    "width": 900,
    "height": 601
  },
  "bird": {
    "src": "/scenic-heroes/about/bird.webp",
    "width": 384,
    "height": 297
  }
};
