// Generated by scripts/scenic-heroes/export-assets.mjs; edit sources.json, then export.
export const assets = {
  "desert-768": {
    "src": "/scenic-heroes/projects/desert-768.webp",
    "width": 768,
    "height": 512
  },
  "desert-1280": {
    "src": "/scenic-heroes/projects/desert-1280.webp",
    "width": 1280,
    "height": 853
  },
  "desert-1536": {
    "src": "/scenic-heroes/projects/desert-1536.webp",
    "width": 1536,
    "height": 1024
  },
  "arch": {
    "src": "/scenic-heroes/projects/arch.webp",
    "width": 1000,
    "height": 954
  },
  "sandbank": {
    "src": "/scenic-heroes/projects/sandbank.webp",
    "width": 1300,
    "height": 504
  },
  "compass": {
    "src": "/scenic-heroes/projects/compass.webp",
    "width": 384,
    "height": 392
  },
  "beetle": {
    "src": "/scenic-heroes/projects/beetle.webp",
    "width": 256,
    "height": 173
  },
  "sand-cover": {
    "src": "/scenic-heroes/projects/sand-cover.webp",
    "width": 384,
    "height": 142
  }
};
