// Generated by scripts/scenic-heroes/export-assets.mjs; edit sources.json, then export.
export const assets = {
  "city-768": {
    "src": "/scenic-heroes/research/city-768.webp",
    "width": 768,
    "height": 512
  },
  "city-1280": {
    "src": "/scenic-heroes/research/city-1280.webp",
    "width": 1280,
    "height": 853
  },
  "city-1536": {
    "src": "/scenic-heroes/research/city-1536.webp",
    "width": 1536,
    "height": 1024
  },
  "facade": {
    "src": "/scenic-heroes/research/facade.webp",
    "width": 797,
    "height": 1882
  },
  "middle-block": {
    "src": "/scenic-heroes/research/middle-block.webp",
    "width": 880,
    "height": 587
  },
  "rooftop": {
    "src": "/scenic-heroes/research/rooftop.webp",
    "width": 1300,
    "height": 300
  },
  "signal": {
    "src": "/scenic-heroes/research/signal.webp",
    "width": 420,
    "height": 499
  },
  "shuttle": {
    "src": "/scenic-heroes/research/shuttle.webp",
    "width": 420,
    "height": 165
  },
  "vapor": {
    "src": "/scenic-heroes/research/vapor.webp",
    "width": 720,
    "height": 175
  }
};
